postgres:
  image: postgres:alpine
  environment:
    POSTGRES_USER: mobydock
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - ~/srv/.docker-volumes/mobydock-rails/postgresql/data:/var/lib/postgresql/data

redis:
  image: redis:alpine
  ports:
    - '6379:6379'
  volumes:
    - ~/srv/.docker-volumes/mobydock-rails/redis/data:/var/lib/redis/data

mobydock-rails:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/srv/mobydock
  ports:
    - '8000:8000'
  env_file:
    - .mobydock.env
